ALTER TABLE "documents"
ADD COLUMN "originalName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "sizeBytes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "checksumSha256" TEXT NOT NULL DEFAULT '';

ALTER TABLE "documents"
ALTER COLUMN "originalName" DROP DEFAULT,
ALTER COLUMN "sizeBytes" DROP DEFAULT,
ALTER COLUMN "checksumSha256" DROP DEFAULT;
